sudo: true
dist: bionic
language: generic
cache: apt

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/texlive'
    packages:
      - wget
      - freeglut3
      - ghostscript
      - tree
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-science
      - texlive-bibtex-extra
      - asymptote
      - latexmk
      - biber

before_script:
    - mkdir asy

script:
    - pdflatex -interaction=batchmode notes-on-FA.tex
    - asy -nosafe -o asy/ asy/notes-on-FA-*.asy -v
    - biber Napkin
    - pdflatex -interaction=batchmode notes-on-FA.tex
    - pdflatex -interaction=batchmode notes-on-FA.tex
    - pdflatex -interaction=batchmode notes-on-FA.tex
    - pdflatex -interaction=batchmode notes-on-FA.tex
    # ...
    # latexmk -pdf -halt-on-error -quiet -interaction=batchmode

before_deploy:
    - mkdir dist
    - mv notes-on-FA.pdf dist/
    - mv notes-on-FA.log dist/
    - mkdir dist/asy/
    - mv asy/*.pdf dist/asy/
    - cd dist/
    - ls
    - tree -H '.' -I "index.html" -D --charset utf-8 -T "notes-on-FA" > index.html

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $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
    local-dir: dist/
    keep-history: false
    on:
        branch: main